name: tech-frontiers
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - _pytorch_select
  - matplotlib
  - numpy
  - pandas
  - pytorch
  - scikit-learn
  - scipy
  - seaborn
  - plotly
  - nbformat
  - hmmlearn
